### ISSUE TITLE
Deprecation Error: will break in Foundry v12

### ISSUE THREAD

**Issue by fluxxdog** [SDoehren/tension-pool#41]
**Describe the bug**
Tension Pool throws an error as follows:
```Error: You are accessing BasePackage#data which is now deprecated in favor of referencing schema fields directly on the BasePackage instance.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:2059:19)
    at get data [as data] (commons.js:14395:7)
    at Object.fn (tension-pool.js:106:94)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at Game.setupGame (foundry.js:8746:11)
    at async Game._initializeGameView (foundry.js:9990:5)
    at async Game.initialize (foundry.js:8650:5)
```

**Foundry (please complete the following information):**
 - Foundry: 11.315 (Stable)
 - System: dnd5e 3.0.2
 - Module Version: 0063

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Foundry (Electron)

**Additional context**
This can be fixed locally by changing the symbol in question to `game.modules.get("tension-pool").version` as well as several lines below it.

**Comment by SDoehren** [comment]
Merged and released, thank you for your help.
